deployment:
  tasks:
    - export NODE_ENV=production
    - /opt/cpanel/ea-nodejs16/bin/npm install
    - /opt/cpanel/ea-nodejs16/bin/npm run build
    - rm -rf public_html/*
    - cp -r build/* public_html/